DROP TABLE IF EXISTS screening;
DROP TABLE IF EXISTS program_programmers;
DROP TABLE IF EXISTS program_staff;
DROP TABLE IF EXISTS program;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(40) NOT NULL,
  full_name VARCHAR(200)
);

CREATE TABLE program (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(4000),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  creation_date TIMESTAMP NOT NULL,
  state VARCHAR(40) NOT NULL,
  creator_id BIGINT,
  CONSTRAINT fk_program_creator FOREIGN KEY (creator_id) REFERENCES users(id)
);

CREATE TABLE program_programmers (
  program_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  PRIMARY KEY (program_id, user_id),
  CONSTRAINT fk_pp_program FOREIGN KEY (program_id) REFERENCES program(id) ON DELETE CASCADE,
  CONSTRAINT fk_pp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE program_staff (
  program_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  PRIMARY KEY (program_id, user_id),
  CONSTRAINT fk_ps_program FOREIGN KEY (program_id) REFERENCES program(id) ON DELETE CASCADE,
  CONSTRAINT fk_ps_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE screening (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creation_date TIMESTAMP NOT NULL,
  program_id BIGINT NOT NULL,
  state VARCHAR(40) NOT NULL,

  film_title VARCHAR(255),
  film_cast VARCHAR(2000),
  film_genres VARCHAR(500),
  film_duration_minutes INT NOT NULL,

  auditorium_name VARCHAR(255),
  start_time TIMESTAMP,
  end_time TIMESTAMP,

  submitter_id BIGINT,
  handler_id BIGINT,

  review_score INT,
  review_comments VARCHAR(4000),

  approval_notes VARCHAR(4000),
  rejection_reason VARCHAR(4000),

  final_submitted BOOLEAN NOT NULL,

  CONSTRAINT fk_screening_program FOREIGN KEY (program_id) REFERENCES program(id) ON DELETE CASCADE,
  CONSTRAINT fk_screening_submitter FOREIGN KEY (submitter_id) REFERENCES users(id),
  CONSTRAINT fk_screening_handler FOREIGN KEY (handler_id) REFERENCES users(id)
);


INSERT INTO users (id, username, password, role, full_name) VALUES
(1, 'visitor',   '$2b$10$9uiHH44OCKyhjNPcjk.gfOP8u5QCO5mrfZdmlL2j5jmwG3YutSyre', 'VISITOR',   'Visitor User'),
(2, 'user1',     '$2b$10$drT5lVAhFaS0LNPo3QpisuGeSIWvq08LXtktxXJG5/3L8IbG0ItyG', 'USER',      'User One'),
(3, 'prog1',     '$2b$10$vnGCdTFuR/NtS3EaTpCMgupa4OEwQVyiFww7cC9ez0ECH81z9yq/6', 'PROGRAMMER','Programmer One'),
(4, 'staff1',    '$2b$10$fIz5Hgyfs8Dpr7HDtJs4Q.1G7rPDTBd5wlTlC1tVLPbXJhb3Bgt7K', 'STAFF',     'Staff One'),
(5, 'submitter', '$2b$10$hZZiPt9jGUBtXeCL8r/HbOqwAm/wDHaJ/NUo1lDjEz4ddKzXeEczK', 'SUBMITTER', 'Submitter One');


INSERT INTO program (id, name, description, start_date, end_date, creation_date, state, creator_id)
VALUES (1, 'Submission Program', 'Program in SUBMISSION state', DATE '2026-01-01', DATE '2026-02-01', CURRENT_TIMESTAMP, 'SUBMISSION', 3);

INSERT INTO program (id, name, description, start_date, end_date, creation_date, state, creator_id)
VALUES (2, 'Assignment Program', 'Program in ASSIGNMENT state', DATE '2026-02-10', DATE '2026-03-10', CURRENT_TIMESTAMP, 'ASSIGNMENT', 3);

INSERT INTO program (id, name, description, start_date, end_date, creation_date, state, creator_id)
VALUES (3, 'Review Program', 'Program in REVIEW state', DATE '2026-03-15', DATE '2026-04-15', CURRENT_TIMESTAMP, 'REVIEW', 3);


INSERT INTO program_programmers (program_id, user_id) VALUES
(1, 3), (2, 3), (3, 3);

INSERT INTO program_staff (program_id, user_id) VALUES
(1, 4), (2, 4), (3, 4);


INSERT INTO screening (
  id, creation_date, program_id, state,
  film_title, film_cast, film_genres, film_duration_minutes,
  auditorium_name, start_time, end_time,
  submitter_id, handler_id,
  review_score, review_comments,
  approval_notes, rejection_reason,
  final_submitted
) VALUES (
  1, CURRENT_TIMESTAMP, 1, 'CREATED',
  'Inception', 'Leonardo DiCaprio', 'Sci-Fi', 148,
  'Hall 1', TIMESTAMP '2026-01-15 18:00:00', TIMESTAMP '2026-01-15 20:28:00',
  5, NULL,
  NULL, NULL,
  NULL, NULL,
  FALSE
);

INSERT INTO screening (
  id, creation_date, program_id, state,
  film_title, film_cast, film_genres, film_duration_minutes,
  auditorium_name, start_time, end_time,
  submitter_id, handler_id,
  review_score, review_comments,
  approval_notes, rejection_reason,
  final_submitted
) VALUES (
  2, CURRENT_TIMESTAMP, 2, 'SUBMITTED',
  'The Matrix', 'Keanu Reeves', 'Action,Sci-Fi', 136,
  'Hall 2', TIMESTAMP '2026-02-20 21:00:00', TIMESTAMP '2026-02-20 23:16:00',
  5, NULL,
  NULL, NULL,
  NULL, NULL,
  FALSE
);

INSERT INTO screening (
  id, creation_date, program_id, state,
  film_title, film_cast, film_genres, film_duration_minutes,
  auditorium_name, start_time, end_time,
  submitter_id, handler_id,
  review_score, review_comments,
  approval_notes, rejection_reason,
  final_submitted
) VALUES (
  3, CURRENT_TIMESTAMP, 3, 'REVIEWED',
  'Interstellar', 'Matthew McConaughey', 'Drama,Sci-Fi', 169,
  'Hall 3', TIMESTAMP '2026-03-20 19:00:00', TIMESTAMP '2026-03-20 21:49:00',
  5, 4,
  8, 'Strong recommendation',
  NULL, NULL,
  FALSE
);


ALTER TABLE program ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE screening ALTER COLUMN id RESTART WITH 1000;
ALTER TABLE users ALTER COLUMN id RESTART WITH 1000;
